---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs-hello
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: nodejsapi
          image: james510/nodejs:v2
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 5000
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 5000
            initialDelaySeconds: 10
            

---
apiVersion: v1
kind: Service
metadata:
  name: nodejsapi-service
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: api
